name: Build and deploy

on:
  push:
    branches:
      # Push events to gh-pages branch
      - gh-pages

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: shalzz/zola-deploy-action@v0.11.0
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
